//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BayazitovObuv
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bayazitov_Shoes1Entities : DbContext
    {
        private static Bayazitov_Shoes1Entities _context;

        public static Bayazitov_Shoes1Entities GetContext()
        {
            if (_context == null)
                _context = new Bayazitov_Shoes1Entities();
            return _context;
        }

        public Bayazitov_Shoes1Entities()
            : base("name=Bayazitov_Shoes1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Manufactures> Manufactures { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Sizes> Sizes { get; set; }
        public virtual DbSet<StockItems> StockItems { get; set; }
        public virtual DbSet<Subcategories> Subcategories { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<OrderProducts> OrderProducts { get; set; }
    }
}
