//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BayazitovObuv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.StockItems = new HashSet<StockItems>();
        }
    
        public int ID_Product { get; set; }
        public string ProductName { get; set; }
        public int ID_Subcategory { get; set; }
        public int ID_Manufacture { get; set; }
        public string ProductDescription { get; set; }
        public string ProductComposition { get; set; }
        public decimal ProductCost { get; set; }
        public int ID_Category { get; set; }
        public string ProductImage { get; set; }

        public string ProductImagePath
        {
            get
            {
                if (ProductImage == null)
                    return null;
                return "img/" + ProductImage;
            }
        }

        public virtual Categories Categories { get; set; }
        public virtual Manufactures Manufactures { get; set; }
        public virtual Subcategories Subcategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockItems> StockItems { get; set; }
    }
}
