//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BayazitovObuv
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockItems()
        {
            this.OrderProducts = new HashSet<OrderProducts>();
        }
    
        public int ID_Item { get; set; }
        public int ID_Product { get; set; }
        public int ID_Size { get; set; }
        public int ItemsQuantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProducts> OrderProducts { get; set; }
        public virtual Products Products { get; set; }
        public virtual Sizes Sizes { get; set; }
    }
}
